import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Card from "../components/card/card";
import { PrismaClient } from "@prisma/client";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Camlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card posts={posts} />
    </>
  );
}

export const getStaticProps = async () => {
  const prisma = new PrismaClient();
  const posts = await prisma.post.findMany();
  const newPosts = posts.map((v) => ({
    ...v,
    createdAt: JSON.stringify(v.createdAt),
    updateAt: JSON.stringify(v.updateAt),
  }));
  console.log(newPosts);
  // const res = await fetch(
  //   "https://jsonplaceholder.typicode.com/posts?_start=0&_end=14"
  // );
  // const posts = await res.json();
  // console.log(posts);
  return {
    props: {
      posts: newPosts,
    },
  };
};
