import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Card from "../components/card/card";
import { PrismaClient } from "@prisma/client";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Camlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card posts={posts} />
    </>
  );
}

export const getStaticProps = async () => {
  const prisma = new PrismaClient();
  const posts = await prisma.post.findMany({
    orderBy: {
      id: "desc",
    },
    take: 8,
  });
  const newPosts = posts.map((v) => ({
    ...v,
    createdAt: JSON.stringify(v.createdAt),
    updateAt: JSON.stringify(v.updateAt),
  }));
  return {
    props: {
      posts: newPosts,
    },
  };
};
