import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/layout/nav";
import Footer from "../components/layout/footer";
import MainContainer from "../components/layout/container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Camlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
